language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install nose coveralls
script:
  - nosetests --with-doctest --doctest-options=+IGNORE_EXCEPTION_DETAIL --with-coverage --cover-package=norman --verbose
after_success:
  - coveralls
